import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  
  En: {
    translation: {
      "Products":"Products",
      "Buy Crypto":"Buy Crypto",
      "Markets":"Markets",
      "Trade":"Trade",
      "Support":"Support",
      "Login":"Login",
      "Register":"Register",
      "Wallet":"Wallet",
      "Buy & Sell Crypto with":"Buy & Sell Crypto with",
      "MGL Exchange":"MGL Exchange",
      "Join the world's largest crypto exchange":"Join the world's largest crypto exchange",
      "Market trend":"Market trend",
      "Buy & Sell Crypto with MGL Exchange":"Buy & Sell Crypto with MGL Exchange",
      "Register Now":"Register Now",
      "Easy to Trade":"Easy to Trade",
      "Own cryptocurrency with as little as USD $10":"Own cryptocurrency with as little as USD $10",
      "Many Payment Methods":"Many Payment Methods",
      "Pay via online banking, credit card or P2P":"Pay via online banking, credit card or P2P",
      "100% Secure":"100% Secure",
      "Your tokens are stored in your private wallet on the blockchain, not on our server for maximum security and privacy.":"Your tokens are stored in your private wallet on the blockchain, not on our server for maximum security and privacy.",
      "Help & Support":"Help & Support",
      "Step 1":"Step 1",
      "Get Started":"Get Started",
      "Alert":"Alert",
      "Already registered": "Already registered",
      "Step 2":"Step 2",
      "Confirmation":"Confirmation",
      "Get in touch. Stay in touch.":"Get in touch. Stay in touch.",
      "Blog":"Blog",
      "Community":"Community",
      "Got a problem? Just get in touch. Our support team is available 24/7.":"Got a problem? Just get in touch. Our support team is available 24/7.",
      "News and updates from the world's leading cryptocurrency exchange.":"News and updates from the world's leading cryptocurrency exchange.",
      "MGL is global. Join the discussion in our worldwide communities.":"MGL is global. Join the discussion in our worldwide communities.",
      "Starting trading now":"Starting trading now",
      "Trade Now":"Trade Now",
      "Step 3":"Step 3",
      "Identity Verification":"Баталгаажуулах",
      "Step 4":"Step 4",
      "Buy Cryptocurrency":"Buy Cryptocurrency",
      "Step 5":"Step 5",
      "Sell Cryptocurrency":"Sell Cryptocurrency",
      "Step 6":"Step 6",
      "Send and Receive":"Send and Receive",
      "Get Started with 3 Steps":"Get Started with 3 Steps",
      "Create an account":"Create an account",
      "Verify your account":"Verify your account",
      "Start buying and selling":"Start buying and selling",
      "Portfolio":"Portfolio",
      "Send":"Send",
      "Activity":"Activity",
      "Balance":"Balance",
      "Total Price":"Total Price",
      "QR Code":"QR Code",
      "Wallet Address":"Wallet Address",
      "Assets":"Assets",
      "Tokens":"Tokens",
      "Collectibles":"Collectibles",
      "Name":"Name",
      "Price":"Price",
      "Search":"Search",
      "Add Token":"Add Token",
      "Transactions":"Transactions",
      "Disconnect Wallet":"Disconnect Wallet",
      "Amount":"Amount",
      "MAX":"MAX",
      "Type":"Type",
      "Token":"Token",
      "To Address":"To Address",
      "Memo (Optional)":"Memo (Optional)",
      "Transaction fee":"Transaction fee",
      "Total MGL":"Total MGL",
      "Insufficient funds.":"Insufficient funds.",
      "View Key Phrase":"View Key Phrase",
      "View Private Key":"View Private Key",
      "Verify Password":"Verify Password",
      "enter password here":"enter password here",
      "Confirm":"Confirm",
      "Email verification":"Email verification",
      "Your Email verification code is":"Your Email verification code is",
      "MGL Exchange: Tokens received":"MGL Exchange: Tokens received",
      "You have received [Quantity of token] [name of token] tokens in your wallet.":"You have received [Quantity of token] [name of token] tokens in your wallet.",
      "MGL Exchange: Tokens sent":"MGL Exchange: Tokens sent",
      "You have sent [Quantity of tokens] [name of tokens] to [Address]":"You have sent [Quantity of tokens] [name of tokens] to [Address]",
      "Identify Verification":"Identify Verification",
      "Profile":"Profile",
      "Log out":"Log out",
      "Log In":"Log In",
      "Credit/Debit Card":"Credit/Debit Card",
      "Buy crypto via card":"Buy crypto via card",
      "P2P Trading":"P2P Trading",
      "Bank transfer and 100+ options":"Bank transfer and 100+ options",
      "Crash Balance":"Crash Balance",
      "Buy crypto with your EUR balance":"Buy crypto with your EUR balance",
      "Exchange":"Exchange",
      "Institutional Services":"Institutional Services",
      "Swap":"Swap",
      "Academy":"Academy",
      "Charity":"Charity",
      "LaunchPad":"LaunchPad",
      "Where do you live?":"Where do you live?",
      "Before we start, please enter your current location of residence.":"Before we start, please enter your current location of residence.",
      "Country/Area of Residence":"Country/Area of Residence",
      "The registration process is subject to change based on the information you provide.":"The registration process is subject to change based on the information you provide.",
      "Create MGL Account":"Create MGL Account",
      "Create Account":"Create Account",
      "I have read and agree to MGL's Terms of Service":"I have read and agree to MGL's Terms of Service",
      "Already registered?":"Already registered?",
      "E-mail verification code":"E-mail verification code",
      "E-mail address":"E-mail address",
      "confirm password":"confirm password",
      "Invite Code(Optional)":"Invite Code(Optional)",
      "MGL Wallet is a simple, secure, non-custodial wallet for storing token assets.":"MGL Wallet is a simple, secure, non-custodial wallet for storing token assets.",
      "WELCOME BACK!":"WELCOME BACK!",
      "Access your existing MGL wallet here":"Access your existing MGL wallet here",
      "NEW TO MGL WALLET?":"NEW TO MGL WALLET?",
      "Create a new wallet to trade assets.":"Create a new wallet to trade assets.",
      "CREATE NEW WALLET":"CREATE NEW WALLET",
      "ACCESS WALLET":"ACCESS WALLET",
      "How do you want to access your wallet?":"How do you want to access your wallet?",
      "Don't have a wallet?":"Don't have a wallet?",
      "Private Key":"Private Key",
      "Mnemonic Key Phrase":"Mnemonic Key Phrase",
      "Cancel":"Cancel",
      "Generate a new key phrase to setup your MGL Wallet.":"Generate a new key phrase to setup your MGL Wallet.",
      "Already have a wallet?":"Already have a wallet?",
      "GENERATE KEY PHRASE":"GENERATE KEY PHRASE",
      "REGENERATE":"REGENERATE",
      "This is your key phrase.":"This is your key phrase.",
      "Use these 12 words in sequential order to recover your MGL Wallet":"Use these 12 words in sequential order to recover your MGL Wallet",
      "Forgot password?":"Forgot password?",
      "Register now":"Register now",
      "ATTENTION!":"ATTENTION!",
      "STORE THIS KEY PHRASE IN A SECURE LOCATION. ANYONE WITH THIS KEY PHRASE CAN ACCESS YOUR MGL WALLET. THERE IS NO WAY TO RECOVER LOST KEY PHRASES.":"STORE THIS KEY PHRASE IN A SECURE LOCATION. ANYONE WITH THIS KEY PHRASE CAN ACCESS YOUR MGL WALLET. THERE IS NO WAY TO RECOVER LOST KEY PHRASES.",
      "CONGRATULATION!":"CONGRATULATION!",
      "It's time to access your MGL Wallet.":"It's time to access your MGL Wallet.",
      "Fill in Mnemonic Phrase Below":"Fill in Mnemonic Phrase Below",
      "Verify Mnemonic":"Verify Mnemonic",
      "Please check mnemonic phrases.":"Please check mnemonic phrases.",
      "Verify":"Verify",
      "Preview":"Preview",
      "Enter your MNEMONIC phrase":"Enter your MNEMONIC phrase",
      "Hit ‘SPACE’ after every successful word entry.":"Hit ‘SPACE’ after every successful word entry.",
      "Back":"Back",
      "to Exchange":"to Exchange",
      "Total":"Total",
      "Token Contract Address":"Token Contract Address",
      "Token Name":"Token Name",
      "Token Symbol":"Token Symbol",
      "Decimals of Precision":"Decimals of Precision",
      "Invalid contract address.":"Invalid contract address.",
      "Memo(Optional)":"Memo(Optional)",
      "Memo":"Memo",
      "Gas Price(GWEI)":"Gas Price(GWEI)",
      "gas price":"gas price",
      "Gas Limit":"Gas Limit",
      "gas limit":"gas limit",
      "Confirm Send Token":"Confirm Send Token",
      "Successfully add Token!":"Successfully add Token!",
      "E-mail sent successfully":"E-mail sent successfully",
      "E-mail successfully verified!":"E-mail successfully verified!",
      "E-mail not verified!":"E-mail not verified!",
      "Account successfully created!":"Account successfully created!",
      "Successful":"Successful",
      "Login Failed":"Login Failed",
      "Forgot Password?":"Forgot Password?",
      "Welcome to our site.":"Welcome to our site.",
      "Please input your E-mail!":"Please input your E-mail!",
      "Please enter a correct email address":"Please enter a correct email address",
      "Please input less than 50 characters":"Please input less than 50 characters",
      "Please input your password!":"Please input your password!",
      "Please input more than 8 characters":"Please input more than 8 characters",
      "Invalid Email Address":"Invalid Email Address",
      "Please input your E-mail Verification Code!":"Please input your E-mail Verification Code!",
      "Please input less than 4 characters":"Please input less than 4 characters",
      "incorrect password!":"incorrect password!",
      "The passwords that you entered do not match!":"The passwords that you entered do not match!",
      "Should accept agreement":"Should accept agreement",
      "Success":"Success",
      "Fail!":"Fail!",
      "Account failed!":"Account failed!",
      "Access failed.":"Access failed.",
      "Please log in.":"Please log in.",
      "Access success.":"Access success.",
      "error":"error",
      "Reset Password":"Reset Password",
      "Reset":"Reset",
      "Failed":"Failed",
      "Email Address":"Email Address",
      "Edit Password":"Edit Password",
      "enter your password":"enter your password",
      "enter new password":"enter new password",
      "confirm new password":"confirm new password",
      "Please input your new password!":"Please input your new password!",
      "Buy":"Buy",
      "Buy with MoonPay":"Buy with MoonPay",
      "Instructions":"Instructions",
      "1. Open Moonpay here.":"1. Open Moonpay here.",
      "2. Select currency BUSD (Bep20).":"2. Select currency BUSD (Bep20).",
      "3. Copy your wallet address above and paste here.":"3. Copy your wallet address above and paste here.",
      "4. Follow rest of Moonpay instructions.":"4. Follow rest of Moonpay instructions.",
      "5. Your purchase will take up to 30 mins to arrive in your wallet.":"5. Your purchase will take up to 30 mins to arrive in your wallet.",
      "6. Done!":"6. Done!",
      "Error. Insufficient BUSD to complete this purchase.":"Алдаа. Энэ худалдан авалтыг хийхэд BUSD хүрэлцэхгүй байна.",
      "Purchase complete. Your MGL Coins will be sent to your wallet after the IEO is co mplete.":"Худалдан авалт амжилттай боллоо. IEO дууссаны дараагаар таны MGL койн хэтэвчинд тань орох болно.",
      "P2P: Buy/Sell Your Crypto Locally": "P2P: Buy/Sell Your Crypto Locally",
      "Peer-to-peer exchange is a marketplace where people can trade crypto directly with each other.":"Peer-to-peer exchange is a marketplace where people can trade crypto directly with each other.",
      "Buy":"Buy",
      "Sell":"Sell",
      "Seller": "Seller",
      "Fiat":"Fiat",
      "Refresh":"Refresh",
      "Advertises":"Advertises",
      "Price":"Price",
      "Limit/Available":"Limit/Available",
      "Payment":"Payment",
      "Trade":"Trade",
      "Available":"Available",
      "Cash/Bank transfer":"Cash/Bank transfer",
      "Bank transfer/Cash":"Bank transfer/Cash",
      "Bank transfer":"Bank transfer",
      "Cash": "Cash",
      "Buy MGL":"Buy MGL",
      "Copyright © 2021 All rights reserved.":"Copyright © 2021 All rights reserved.",
      "Buy with MoonPay":"Buy with MoonPay",
      "Instructions":"ЗааInstructionsвар",
      "Open Moonpay here":"Open Moonpay here",
      "Select currency BUSD (BEP20)":"Select currency BUSD (BEP20)",
      "Currency":"Currency",
      "Enter your Binance Smart Chain wallet address":"Enter your Binance Smart Chain wallet address",
      "Copy your wallet address above and paste here":"Copy your wallet address above and paste here",
      "Follow rest of Moonpay instructions":"Follow rest of Moonpay instructions",
      "Your purchase will take up to 30 mins to arrive in your wallet.":"Your purchase will take up to 30 mins to arrive in your wallet.",
      "MGL Verified": "MGL Verified",
      "Terms and conditions": "Terms and conditions",
      "Done!":"Done!",
      "Buy Token":"Buy Token",
      "Buy to":"Buy to",
      "Amount : ":"Amount : ",
      "Input Amount":"Input Amount",
      "Buy from":"Buy from",
      "Lack Fee.":"Lack Fee.",
      "Do you have BNB to complete this transaction?":"Do you have BNB to complete this transaction?",
      "Yes, continue purchase":"Yes, continue purchase",
      "No, send me BNB":"No, send me BNB"
    }
  },
  Mn: {
    translation: {
      "Products":"бүтээгдэхүүн",
      "Buy Crypto":"Крипто худалдаж авах",
      "Markets":"Зах зээл",
      "Trade":"Арилжаа",
      "Support":"Үйлчилгээ",
      "Login":"Нэвтрэх",
      "Register":"Бүртгүүлэх",
      "Wallet":"Хэтэвч",
      "Buy & Sell Crypto with":"MGL биржээр",
      "MGL Exchange":"крипто худалдаж авах, зарах",
      "Join the world's largest crypto exchange":"Дэлхийн хамгийн том крипто биржид нэгдээрэй",
      "Market trend":"Зах зээлийн чиг хандлага",
      "Buy & Sell Crypto with MGL Exchange":"MGL биржээр крипто худалдаж авах, зарах",
      "Register Now":"Одоо бүртгүүлэх",
      "Easy to Trade":"Арилжаа хийхэд хялбар",
      "Own cryptocurrency with as little as USD $10":"Ердөө 10$ оор крипто валют эзэмшээрэй",
      "Many Payment Methods":"Төлбөрийн шийдлүүд",
      "Pay via online banking, credit card or P2P":"Төлбөрөө онлайн банк, кредит карт, P2P-ээр төлөх",
      "100% Secure":"100% баталгаатай",
      "Your tokens are stored in your private wallet on the blockchain, not on our server for maximum security and privacy.":"Таны токен манай серверт биш блокчейн системийн баталгаат хэтэвчинд тань хадгалагдана.",
      "Help & Support":"Тусламж & үйлчилгээ",
      "Step 1":"Алхам 1",
      "Get Started":"Эхлэх",
      "Alert":"Анхааруулга",
      "Already registered": "Аль хэдийн бүртгэгдсэн",
      "Step 2":"Алхам 2",
      "Confirmation":"Зөвшөөрөх",
      "Get in touch. Stay in touch.":"Холбоотой байх. Холбоотой байгаарай.",
      "Blog":"Блог",
      "Community":"Нийгэмлэг",
      "Got a problem? Just get in touch. Our support team is available 24/7.":"Асуудал байна уу? Зүгээр л холбогдоорой. Манай тусламжийн баг 24/7 бэлэн байна.",
      "News and updates from the world's leading cryptocurrency exchange.":"Дэлхийн тэргүүлэгч криптовалют биржийн мэдээ, шинэчлэлтүүд.",
      "MGL is global. Join the discussion in our worldwide communities.":"MGL бол дэлхий нийтийнх. Манай дэлхий даяарх нийгэмлэгүүдийн хэлэлцүүлэгт нэгдээрэй.",
      "Starting trading now":"Одоо арилжаагаа эхлүүлж байна",
      "Trade Now":"Одоо худалдаа хийнэ",
      "Step 3":"Алхам 3",
      "Identity Verification":"Баталгаажуулах",
      "Step 4":"Алхам 4",
      "Buy Cryptocurrency":"Крипто валют худалдаж авах",
      "Step 5":"Алхам 5",
      "Sell Cryptocurrency":"Крипто валют худалдаалах",
      "Step 6":"Алхам 6",
      "Send and Receive":"Илгээх бас хүлээн авах",
      "Get Started with 3 Steps":"3 алхам хийснээр эхлэх",
      "Create an account":"Хаягаа үүсгэнэ",
      "Verify your account":"Хаягаа баталгаажуулна",
      "Start buying and selling":"Худалдан авах, худалдаалж эхлэх",
      "Portfolio":"Багц",
      "Send":"Илгээх",
      "Activity":"Үйл ажиллагаа",
      "Balance":"Үлдэгдэл",
      "Total Price":"Нийт үнэ",
      "QR Code":"QR код",
      "Wallet Address":"Хэтэвчний хаяг",
      "Assets":"Хөрөнгө",
      "Tokens":"Токенууд",
      "Collectibles":"Цуглуулга",
      "Name":"Нэр",
      "Price":"Үнэ",
      "Search":"Хайлт хийх",
      "Add Token":"Токен нэмэх",
      "Transactions":"Гүйлгээнүүд",
      "Disconnect Wallet":"Хэтэвчээ салгах",
      "Amount":"Хэмжээ",
      "MAX":"Хамгийн ихдээ",
      "Type":"Төрөл",
      "Token":"Токен",
      "To Address":"Илгээх хаяг",
      "Memo (Optional)":"Тэмдэглэл үлдээх (заавал биш)",
      "Transaction fee":"Гүйлгээний шимтгэл",
      "Total MGL":"Нийт MGL",
      "Insufficient funds.":"Үлдэгдэл хүрэлцэхгүй байна",
      "View Key Phrase":"Түлхүүр үгийг харах",
      "View Private Key":"Хувийн түлхүүрийг харах",
      "Verify Password":"Нууц үг баталгаажуулалт",
      "enter password here":"Нууц үгээ оруулна уу",
      "Confirm":"Батлах",
      "Email verification":"Имэйл баталгаажуулалт",
      "Your Email verification code is":"Таны имэйл баталгаажуулах код",
      "MGL Exchange: Tokens received":"MGL бирж: Токен хүлээн авсан",
      "You have received [Quantity of token] [name of token] tokens in your wallet.":"Та хэтэвчиндээ [Quantity of token] ширхэг [name of token] токен хүлээн авсан байна",
      "MGL Exchange: Tokens sent":"MGL бирж: Токен илгээсэн",
      "You have sent [Quantity of tokens] [name of tokens] to [Address]":"Та [Quantity of tokens] ширхэг [name of tokens] токен [Address] хаяг руу илгээсэн байна",      
      "Profile":"Профайл",
      "Log out":"Гарах",
      "Log In":"Нэвтрэх",
      "Credit/Debit Card":"Кредит/дебит карт",
      "Buy crypto via card":"Картаар крипто худалдаж аваарай",
      "P2P Trading":"P2P худалдаа",
      "Bank transfer and 100+ options":"Банкны шилжүүлэг болон 100+ сонголт",
      "Crash Balance":"Гэмтлийн үлдэгдэл",
      "Buy crypto with your EUR balance":"Өөрийн еврогийн үлдэгдлээр крипто худалдаж аваарай",
      "Exchange":"Солилцоо",
      "Institutional Services":"Байгууллагын үйлчилгээ",
      "Swap":"Солих",
      "Academy":"Академи",
      "Charity":"Энэрэл",
      "LaunchPad":"Хөөргөх дэвсгэр",
      "E-mail address":"Имэйл хаяг",
      "Forgot password?":"Нууц үгээ мартсан?",
      "Register now":"Яг одоо бүртгүүл",
      "Where do you live?":"Та хаана амьдардаг вэ?",
      "Before we start, please enter your current location of residence.":"та эхлэхээсээ өмнө амьдарч буй улсаа сонгоно уу.",
      "Country/Area of Residence":"Улс/Оршин суугаа газар",
      "The registration process is subject to change based on the information you provide.":"Бүртгэлийн үйл явц нь таны өгсөн мэдээлэлд үндэслэн өөрчлөгдөж болно.",
      "Create MGL Account":"MGL данс үүсгэх",
      "Create Account":"Бүртгэл үүсгэх",
      "I have read and agree to MGL's Terms of Service":"Би MGL-ийн үйлчилгээний нөхцөлийг уншиж, зөвшөөрч байна",
      "Already registered?":"Аль хэдийн бүртгэгдсэн?",
      "E-mail verification code":"Имэйлээр ирсэн баталгаажуулах код",
      "confirm password":"нууц үгээ баталгаажуулна уу",
      "Invite Code(Optional)":"Урилгын код(заавал биш)",
      "MGL Wallet is a simple, secure, non-custodial wallet for storing token assets.":"MGL Wallet бол Крипто хөрөнгийг хадгалахад зориулагдсан энгийн, найдвартай, хэтэвч юм.",
      "WELCOME BACK!":"Тавтай морилно уу",
      "Access your existing MGL wallet here":"Өөрийн MGL хэтэвчинд нэвтрэх",
      "NEW TO MGL WALLET?":"Шинэ хэрэглэгч",
      "Create a new wallet to trade assets.":"Шинээр хэтэвч үүсгэх",
      "CREATE NEW WALLET":"Шинээр үүсгэх",
      "ACCESS WALLET":"Нэвтрэх",
      "How do you want to access your wallet?":"Та хэтэвчиндээ хэрхэн хандахыг хүсэж байна вэ?",
      "Don't have a wallet?":"Түрийвч байхгүй юу?",
      "Private Key":"Хувийн түлхүүр",
      "Mnemonic Key Phrase":"Мнемоник түлхүүр хэллэг",
      "Cancel":"Цуцлах",
      "Generate a new key phrase to setup your MGL Wallet.":"MGL хэтэвчнийхээ нууц үгийг үүсгэнэ үү",
      "Already have a wallet?":"Бүртгэлтэй хэрэглэгч?",
      "GENERATE KEY PHRASE":"Нууц үг үүсгэх",
      "REGENERATE":"ДАХИН ҮҮСГЭХ",
      "This is your key phrase.":"Энэ таны нууц үг.",
      "Use these 12 words in sequential order to recover your MGL Wallet":"MGL хэтэвчээ сэргээхийн тулд эдгээр 12 үгийг дарааллаар нь оруулна уу",
      "ATTENTION!":"АНХААР!",
      "STORE THIS KEY PHRASE IN A SECURE LOCATION. ANYONE WITH THIS KEY PHRASE CAN ACCESS YOUR MGL WALLET. THERE IS NO WAY TO RECOVER LOST KEY PHRASES.":"ЭДГЭЭР ҮГСИЙГ ЭЗЭМШИГЧ НЬ ТАНЫ ХЭТЭВЧИНД НЭВТРЭХ ЭРХТЭЙ БОЛНО. ТИЙМЭЭС ТА НУУЦ ҮГНИЙХЭЭ АЮУЛГҮЙ БАЙДЛЫГ ХАНГАНА УУ. ЭДГЭЭР ҮГСИЙГ АЛДСАН ТОХИОЛДОЛД СЭРГЭЭХ БОЛОМЖГҮЙГ АНХААРНА УУ",
      "CONGRATULATION!":"БАЯР ХҮРГЭЕ!",
      "It's time to access your MGL Wallet.":"MGL Wallet руугаа нэвтрэх цаг боллоо.",
      "Fill in Mnemonic Phrase Below":"Доорх Mnemonic хэллэгийг бөглөнө үү",
      "Verify Mnemonic":"Mnemonic-г баталгаажуулна уу",
      "Please check mnemonic phrases.":"Мнемоник хэллэгийг шалгана уу.",
      "Verify":"Баталгаажуулах",
      "Preview":"Урьдчилан үзэх",
      "Enter your MNEMONIC phrase":"MNEMONIC хэллэгээ оруулна уу",
      "Hit ‘SPACE’ after every successful word entry.":"Амжилттай оруулсан үг бүрийн дараа ‘SPACE’ дээр дарна уу.",
      "Back":"Бирж",
      "to Exchange":"рүү буцах",
      "Total":"Нийт",
      "Token Contract Address":"Токен гэрээний хаяг",
      "Token Name":"Токен нэр",
      "Token Symbol":"Токен тэмдэг",
      "Decimals of Precision":"Нарийвчлалын аравтын тоо",
      "Invalid contract address.":"Гэрээний хаяг буруу байна.",
      "Memo(Optional)":"Санамж(заавал биш)",
      "Memo":"Санамж",
      "Gas Price(GWEI)":"Хийн үнэ (GWEI)",
      "gas price":"хийн үнэ",
      "Gas Limit":"Хийн хязгаар",
      "gas limit":"хийн хязгаар",
      "Confirm Send Token":"Токен илгээхийг баталгаажуулна уу",
      "Successfully add Token!":"Токеныг амжилттай нэмээрэй!",
      "E-mail sent successfully":"Имэйлийг амжилттай илгээлээ",
      "E-mail successfully verified!":"Имэйлийг амжилттай баталгаажууллаа!",
      "E-mail not verified!":"Имэйлийг баталгаажуулаагүй!",
      "Account successfully created!":"Бүртгэл амжилттай үүсгэгдсэн!",
      "Successful":"Амжилттай",
      "Login Failed":"Нэвтрэх амжилтгүй боллоо",
      "Forgot Password?":"Нууц үгээ мартсан?",
      "Welcome to our site.":"Манай сайтад тавтай морил.",
      "Please input your E-mail!":"Имэйлээ оруулна уу!",
      "Please enter a correct email address":"Зөв имэйл хаяг оруулна уу",
      "Please input less than 50 characters":"50-аас бага тэмдэгт оруулна уу",
      "Please input your password!":"Нууц үгээ оруулна уу!",
      "Please input more than 8 characters":"8-аас дээш тэмдэгт оруулна уу",
      "Invalid Email Address":"Хүчингүй мэйл хаяг",
      "Please input your E-mail Verification Code!":"И-мэйл баталгаажуулах кодоо оруулна уу!",
      "Please input less than 4 characters":"4-с бага тэмдэгт оруулна уу",
      "incorrect password!":"нууц үг тохирсонгүй!",
      "The passwords that you entered do not match!":"Таны оруулсан нууц үг таарахгүй байна!",
      "Should accept agreement":"Гэрээг хүлээн зөвшөөрөх ёстой",
      "Success":"Амжилт",
      "Fail!":"Амжилтгүй!",
      "Account failed!":"Бүртгэл амжилтгүй боллоо!",
      "Access failed.":"Хандалт амжилтгүй боллоо.",
      "Please log in.":"Та нэвтэрнэ үү.",
      "Access success.":"Амжилтанд нэвтрэх.",
      "error":"алдаа",
      "Reset Password":"Нууц үгээ анхны байдалд нь оруулж",
      "Reset":"Дахин тохируулах",
      "Failed":"Амжилтгүй",
      "Identify Verification":"Иргэний үнэмлэх баталгаажуулалт",
      "Email Address":"Имэйл хаяг",
      "Edit Password":"Нууц үгээ засах",
      "enter your password":"нууц үгээ оруулна уу",
      "enter new password":"шинэ нууц үг оруулна уу",
      "confirm new password":"Шинэ нууц үг баталгаажуулах",
      "Please input your new password!":"Шинэ нууц үгээ оруулна уу!",
      "Buy":"худалдаж авах",
      "Buy with MoonPay":"MoonPay-ээр худалдаж аваарай",
      "Instructions":"Зааварчилгаа",
      "1. Open Moonpay here.":"1. Moonpay-г энд нээнэ үү.",
      "2. Select currency BUSD (Bep20).":"2. Валют сонгох BUSD (Bep20).",
      "3. Copy your wallet address above and paste here.":"3. Дээрх түрийвчний хаягаа хуулж аваад энд дарна уу.",
      "4. Follow rest of Moonpay instructions.":"4. Moonpay-н бусад зааврыг дагана уу.",
      "5. Your purchase will take up to 30 mins to arrive in your wallet.":"5. Таны худалдан авалт түрийвчиндээ ирэхэд 30 минут зарцуулагдана.",
      "6. Done!":"6. Дууслаа!",
      "Error. Insufficient BUSD to complete this purchase.":"Алдаа. Энэ худалдан авалтыг хийхэд BUSD хүрэлцэхгүй байна.",
      "Purchase complete. Your MGL Coins will be sent to your wallet after the IEO is co mplete.":"Худалдан авалт амжилттай боллоо. IEO дууссаны дараагаар таны MGL койн хэтэвчинд тань орох болно.",
      "P2P: Buy/Sell Your Crypto Locally": "P2P: Крипто худалдан ав/Зар",
      "Peer-to-peer exchange is a marketplace where people can trade crypto directly with each other.":"Peer-to-peer бирж нь хүмүүс хоорондоо шууд крипто арилжаа хийх боломжтой зах зээл юм.",
      "Buy":"Худалдаж авах",
      "Sell":"Зарах",
      "Seller": "худалдагч",
      "Fiat":"Мөнгөн тэмдэгт",
      "Refresh":"Дахин ачаалах",
      "Advertises":"Нээлттэй арилжаанууд",
      "Price":"Үнэ",
      "Limit/Available":"Хязгаар/Боломжтой",
      "Payment":"Төлбөр",
      "Trade":"Худалдаа",
      "Available":"Боломжтой",
      "Cash/Bank transfer":"Бэлэн мөнгө/Банкны шилжүүлэг",
      "Bank transfer/Cash":"Банкны шилжүүлэг/Бэлэн мөнгө",
      "Bank transfer":"Банкны шилжүүлэг",
      "Cash": "Бэлэн мөнгө",
      "Buy MGL":"MGL худалдаж авах",
      "Copyright © 2021 All rights reserved.":"© 2021 Зохиогчийн эрх хуулиар хамгаалагдсан.",
      "Buy with MoonPay":"MoonPay-ээр худалдан авалт хийх",
      "Instructions":"Заавар",
      "Open Moonpay here":"Moonpay оруулах",
      "Select currency BUSD (BEP20)":"BUSD (Bep20) валютыг сонгоорой",
      "Currency":"Валют",
      "Enter your Binance Smart Chain wallet address":"Binance Smart Chain хэтэвчний хаягаа оруулаарай",
      "Copy your wallet address above and paste here":"Хэтэвчний хаягаа хуулаад энд хийнэ үү",
      "Follow rest of Moonpay instructions":"Moonpay-ын үлдсэн зааврыг дагаарай",
      "Your purchase will take up to 30 mins to arrive in your wallet.":"Таны худалдан авалт 30 минутын дараа хэтэвчинд тань орно.",
      "MGL Verified": "MGL баталгаажуулсан",
      "Terms and conditions": "Нөхцөл, нөхцөл",
      "Done!":"Амжилттай боллоо!",
      "Buy Token":"Койн худалдаж авах",
      "Buy to":"Худалдаж авах",
      "Amount : ":"Дүн : ",
      "Input Amount":"Дүн оруулах",
      "Buy from":"Худалдах",
      "Lack Fee.":"Төлбөрийн хомсдол.",
      "Do you have BNB to complete this transaction?":"Танд энэ гүйлгээг гүйцэтгэх хэмжээний BNB байгаа юу?",
      "Yes, continue purchase":"Тийм, үргэлжлүүлэх",
      "No, send me BNB":"Үгүй, надад BNB илгээнэ үү"
    }
  }
};

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem('locale') || "Mn",
  fallbackLng: ['En', 'Mn'],
  interpolation: {
    escapeValue: false
  }
});

export default i18n;